stages:
  - usuario
  - login
  - conta
default:
  image: maven:3.6.3-jdk-8-slim
  services:
    - selenium/standalone-chrome
usuario:
  stage: usuario
  script:
    - mvn test -Dtest=CadastroUsuarioTest

login:
  stage: login
  script:
    - mvn test -Dtest=LoginTest

conta:
  stage: conta
  script:
    - mvn test -Dtest=ContaTest
